/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Desktop: typeof import('./src/components/Desktop.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Input: typeof import('./src/components/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Task: typeof import('./src/components/Task.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Window: typeof import('./src/components/Window.vue')['default']
  }
}
